/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as ResultsAttemptIdRouteImport } from './routes/results.$attemptId'
import { Route as QuizIdRouteImport } from './routes/quiz.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/', path: '/', getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history', path: '/history', getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings', path: '/settings', getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash', path: '/trash', getParentRoute: () => rootRouteImport,
} as any)
const ResultsAttemptIdRoute = ResultsAttemptIdRouteImport.update({
  id: '/results/$attemptId', path: '/results/$attemptId', getParentRoute: () => rootRouteImport,
} as any)
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/quiz/$id', path: '/quiz/$id', getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/trash': typeof TrashRoute
  '/quiz/$id': typeof QuizIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/trash': typeof TrashRoute
  '/quiz/$id': typeof QuizIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/trash': typeof TrashRoute
  '/quiz/$id': typeof QuizIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/history' | '/settings' | '/trash' | '/quiz/$id' | '/results/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/settings' | '/trash' | '/quiz/$id' | '/results/$attemptId'
  id: '__root__' | '/' | '/history' | '/settings' | '/trash' | '/quiz/$id' | '/results/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  TrashRoute: typeof TrashRoute
  QuizIdRoute: typeof QuizIdRoute
  ResultsAttemptIdRoute: typeof ResultsAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/history': { id: '/history'; path: '/history'; fullPath: '/history'; preLoaderRoute: typeof HistoryRouteImport; parentRoute: typeof rootRouteImport }
    '/settings': { id: '/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof SettingsRouteImport; parentRoute: typeof rootRouteImport }
    '/trash': { id: '/trash'; path: '/trash'; fullPath: '/trash'; preLoaderRoute: typeof TrashRouteImport; parentRoute: typeof rootRouteImport }
    '/results/$attemptId': { id: '/results/$attemptId'; path: '/results/$attemptId'; fullPath: '/results/$attemptId'; preLoaderRoute: typeof ResultsAttemptIdRouteImport; parentRoute: typeof rootRouteImport }
    '/quiz/$id': { id: '/quiz/$id'; path: '/quiz/$id'; fullPath: '/quiz/$id'; preLoaderRoute: typeof QuizIdRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute, HistoryRoute, SettingsRoute, TrashRoute, QuizIdRoute, ResultsAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
